HyperSchool/task/HyperSchool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedule.urls'))
]

HyperSchool/task/schedule/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from .views import *

urlpatterns = [
    path('schedule/main/', IndexMenu.as_view(), name='main'),
    path('schedule/course_details/<int:course_id>', CourseDetails.as_view(), name="details"),
    path('schedule/teacher_details/<int:tutor_id>', TutorDetails.as_view(), name="tutor"),
    path('schedule/add_course/', AddCourse.as_view(), name="add_course"),
    path("login/", Login.as_view(), name="login"),
    path("signup/", Signup.as_view(), name="signup"),
]

HyperSchool/task/schedule/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.
class Teacher(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    age = models.IntegerField()
    about = models.TextField()

    def get_absolute_url(self):
        return reverse('tutor', args=(self.pk,))

    def __str__(self):
        return self.name + " " + self.surname


class Course(models.Model):
    title = models.CharField(max_length=50)
    info = models.TextField(max_length=255)
    duration_months = models.IntegerField()
    price = models.IntegerField()
    teacher = models.ManyToManyField(Teacher)

    def get_absolute_url(self):
        return reverse('details', kwargs={'id':self.id, 'title':self.title, 'info':self.info})

    def __str__(self):
        return self.title


class Student(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    age = models.IntegerField()
    course = models.ManyToManyField(Course)

    def __str__(self):
        return self.name + " " + self.surname

HyperSchool/task/schedule/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class SearchForm(forms.Form):
    q = forms.CharField(label='Search', required=False, max_length=32)


class StudentSignUpForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

HyperSchool/task/schedule/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import *
from django.views.generic.detail import DetailView
from .forms import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
# Create your views here.


class IndexMenu(View):

    def get(self, request, **kwargs):
        content = request.GET
        query = content.get('q')
        course_count, courses = Course.objects.all().count(), Course.objects.all()
        form = SearchForm(request.GET)
        if query:
            context = {'course_count': courses.filter(title__contains=query).count(), 'courses': courses.filter(title__contains=query), 'form': form}
            return render(request, 'schedule/index.html', context)

        if query is None or query == "":
            context = {'course_count': course_count, 'courses': courses, 'form': form}
            return render(request, 'schedule/index.html', context)


class CourseDetails(View):
    def get(self, request, **kwargs):
        course_id = kwargs['course_id']
        course = Course.objects.get(pk=course_id)
        teacher = course.teacher.all()
        print(teacher)
        context = {'course': course, 'teachers': teacher}

        return render(request, 'schedule/course_info.html', context)


class TutorDetails(View):
    def get(self, request, **kwargs):
        course_id = kwargs['tutor_id']
        teacher = Teacher.objects.get(pk=course_id)
        context = {'teacher': teacher}
        return render(request, 'schedule/teacher_info.html', context)


class AddCourse(View):
    def get(self, request, **kwargs):
        form = StudentSignUpForm()
        context = {'form': form}
        return render(request, 'schedule/add_course.html', context)

    def post(self, request, **kwargs):
        form = StudentSignUpForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('add_course')


class Login(View):
    def get(self, request):
        form = AuthenticationForm()
        context = {'data': form}
        return render(request, 'schedule/login.html', context)


    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
            return redirect('main')


class Signup(View):
    def get(self, request, *args, **kwargs):
        form = UserCreationForm()
        context = {'data': form}
        return render(request, "schedule/signup.html", context)

    def post(self, request):
        form = UserCreationForm(request.POST)
        context = {'data': form}
        if form.is_valid():
            form.save()
            return redirect('main')
        return redirect('signup')

HyperSchool/task/schedule/templates/schedule/add_course.html
{% extends 'schedule/base.html' %}
{% block body %}
<h1>Apply to the course</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
{% endblock %}

HyperSchool/task/schedule/templates/schedule/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %} {% endblock %}
</head>
<body>
  {% block body %} {% endblock %}
</body>
</html>

HyperSchool/task/schedule/templates/schedule/course_info.html
{% extends 'schedule/base.html' %}
{% block body %}
<h2> Name of the program: {{ course.title }}</h2>

<p> Course description: {{ course.info }} </p>
<p> Course duration: {{ course.duration_months}} months</p>
<p> Course price: ${{ course.price }}</p>
<h2>Already studying: </h2>
<p> {% for teacher in course.teacher.all %}
{% for student in course.student_set.all %}
    {{ student }} </br>
    {% endfor %}
   {% endfor %}
</p>
<h2> Teachers of the course: </h2>
{% for teacher in teachers %}
<p><a href="{{teacher.get_absolute_url}}">{{ teacher.name | add:" "| add:teacher.surname }}</a> </p>
{% endfor %}

<p><h2>Join us!</h2><a href="{% url 'add_course' %}">Apply to the course {{ course.title }} </a></p>
<p><a href="{% url 'main' %}">Go back to the list of courses </a></p>
    <h2>Already studying:</h2>

    {% for student in students %}

        <p>{{ student.name }}</p>

    {% endfor %}
{% endblock %}

HyperSchool/task/schedule/templates/schedule/index.html
{% extends 'schedule/base.html' %}
{% block title %} <title>HyperSchool</title> {% endblock %}


{% block body %}
<h2> HyperSchool</h2>
<p>Hi! Welcome to the site of online HyperSchool!</p>
<p>Feel free to choose any speciality you are interested in!</p>
<p><a href="{% url 'signup' %}">Sign up</a></p>
<p><a href="{% url 'login' %}">Login</a></p>
<form method="get">
  {% csrf_token %}
<!--  <input type="search" name="q" />-->
  {{ form }}
  <input type="submit" value="search" />
</form>
<p>{{ course_count }} courses</p>

  {% for course in courses %}
  <a href="{% url 'details' course.id %}"> {{ course.title }} </a> </br>
  {% endfor %}

{% endblock %}

HyperSchool/task/schedule/templates/schedule/login.html
{% extends 'schedule/base.html' %}
{% block body %}
<form method="POST" action="{% url 'login' %}">
    {% csrf_token %}
    {{ data.as_p }}
    </br>
    <input type="submit" value="Login" />
    </form>
{% endblock %}

HyperSchool/task/schedule/templates/schedule/signup.html
{% extends 'schedule/base.html' %}

{% block body %}
<form method="POST" action="{% url 'signup' %}">
    {% csrf_token %}
    {{ data.as_p }}
    </br>
    <input type="submit" />
    </form>
{% endblock %}

HyperSchool/task/schedule/templates/schedule/teacher_info.html
{% extends 'schedule/base.html' %}
{% block body %}
<h1>Get acquainted!</h1>
<h2> Name : {{ teacher.name}}</h2>
<h2> Surname: {{ teacher.surname}} months</h2>
<h2> Age: {{ teacher.age }}</h2>
<h2> {{ teacher.about }} </h2>

<p><a href="{% url 'main' %}">Go back to the list of courses  </a></p>
{% endblock %}